[
    { "name": "Pierre Dubois", "country": "France", "amount": 238.5, "type": "withdrawn" },
    { "name": "Hiroshi Tanaka", "country": "Japan", "amount": 150.32, "type": "invested" },
    { "name": "Emily Davis", "country": "Canada", "amount": 388.06, "type": "invested" },
    { "name": "Olivia Brown", "country": "United States", "amount": 568.35, "type": "invested" },
    { "name": "Pierre Dubois", "country": "United Kingdom", "amount": 215.18, "type": "withdrawn" },
    { "name": "Liu Wei", "country": "Japan", "amount": 269.0, "type": "withdrawn" },
    { "name": "Pierre Dubois", "country": "United Kingdom", "amount": 639.62, "type": "invested" },
    { "name": "Michael Smith", "country": "United States", "amount": 198.9, "type": "withdrawn" },
    { "name": "Hans Müller", "country": "Italy", "amount": 941.12, "type": "withdrawn" },
    { "name": "James Johnson", "country": "United States", "amount": 338.83, "type": "withdrawn" },
    { "name": "Emily Davis", "country": "Canada", "amount": 778.54, "type": "withdrawn" },
    { "name": "Hiroshi Tanaka", "country": "India", "amount": 564.8, "type": "invested" },
    { "name": "Hans Müller", "country": "Italy", "amount": 974.7, "type": "invested" },
    { "name": "Liu Wei", "country": "Japan", "amount": 288.95, "type": "invested" },
    { "name": "James Johnson", "country": "Mexico", "amount": 984.09, "type": "invested" },
    { "name": "Hans Müller", "country": "Italy", "amount": 167.18, "type": "invested" },
    { "name": "Liu Wei", "country": "India", "amount": 364.28, "type": "invested" },
    { "name": "Lars Eriksen", "country": "United Kingdom", "amount": 412.83, "type": "invested" },
    { "name": "Hiroshi Tanaka", "country": "Japan", "amount": 454.78, "type": "withdrawn" },
    { "name": "Hiroshi Tanaka", "country": "South Korea", "amount": 412.43, "type": "invested" },
    { "name": "Hiroshi Tanaka", "country": "China", "amount": 286.93, "type": "withdrawn" },
    { "name": "Sophie Martin", "country": "France", "amount": 412.67, "type": "withdrawn" },
    { "name": "Ravi Patel", "country": "Japan", "amount": 729.85, "type": "invested" },
    { "name": "John Doe", "country": "Canada", "amount": 338.39, "type": "invested" },
    { "name": "John Doe", "country": "Mexico", "amount": 681.25, "type": "invested" },
    { "name": "Ravi Patel", "country": "India", "amount": 901.24, "type": "withdrawn" },
    { "name": "Lars Eriksen", "country": "Italy", "amount": 431.36, "type": "withdrawn" },
    { "name": "Emily Davis", "country": "Mexico", "amount": 991.0, "type": "invested" },
    { "name": "Ravi Patel", "country": "China", "amount": 384.36, "type": "withdrawn" },
    { "name": "Michael Smith", "country": "Canada", "amount": 491.71, "type": "withdrawn" },
    { "name": "Hans Müller", "country": "United Kingdom", "amount": 507.97, "type": "invested" },
    { "name": "Emily Davis", "country": "United States", "amount": 639.48, "type": "withdrawn" },
    { "name": "Mei Lin", "country": "India", "amount": 799.89, "type": "invested" },
    { "name": "Sophie Martin", "country": "United Kingdom", "amount": 331.5, "type": "withdrawn" },
    { "name": "James Johnson", "country": "United States", "amount": 486.33, "type": "withdrawn" },
    { "name": "Lars Eriksen", "country": "Sweden", "amount": 728.06, "type": "withdrawn" },
    { "name": "Emily Davis", "country": "Mexico", "amount": 367.32, "type": "withdrawn" },
    { "name": "John Doe", "country": "Canada", "amount": 279.6, "type": "invested" },
    { "name": "Ravi Patel", "country": "Singapore", "amount": 641.15, "type": "withdrawn" },
    { "name": "Hiroshi Tanaka", "country": "Japan", "amount": 688.15, "type": "withdrawn" },
    { "name": "Satoshi Nakamoto", "country": "South Korea", "amount": 354.93, "type": "withdrawn" },
    { "name": "John Doe", "country": "Canada", "amount": 737.89, "type": "invested" },
    { "name": "Mei Lin", "country": "India", "amount": 322.34, "type": "invested" },
    { "name": "Satoshi Nakamoto", "country": "Singapore", "amount": 364.83, "type": "withdrawn" }


]
